version: "3.5"

services:
  master-infrared:
    build: .
    image: kainosekai/infrared:master
    container_name: master-infrared
    network_mode: "host"
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 25565:25565/tcp
    volumes:
      - ./configs:/configs
    environment:
      INFRARED_CONFIG_PATH: /configs
