version: "3"

services:
  infrared:
    build: "."
    image: "kainosekai/infrared:latest"
    container_name: "infrared"
    restart: "unless-stopped"
    stdin_open: true
    tty: true
    ports:
      - "25565:25565/tcp"
    volumes:
      - "/usr/local/infrared/configs:/configs"
    expose:
      - "25565"
    environment:
      INFRARED_CONFIG_PATH: "/configs"
