version: "3.5"

services:
  local-infrared:
    build: .
    image: kainosekai/infrared:local
    container_name: local-infrared
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - minecraft
    expose:
      - 25565/tcp
    volumes:
      - ./configs:/configs
    environment:
      INFRARED_CONFIG_PATH: /configs

networks:
  minecraft:
    name: minecraft
