version: "3.5"

services:
  master-infrared:
    build: .
    image: kainosekai/infrared:master
    container_name: master-infrared
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - minecraft
    ports:
      - 25565:25565/tcp
    volumes:
      - ./configs:/configs
    environment:
      INFRARED_CONFIG_PATH: /configs

networks:
  minecraft:
    name: minecraft
